#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define OPTICAR_SYSTEM_FREQUENCY 80000000 // 80 MHz
#define OPTICAR_PWM_FREQUENCY 440
#define OPTICAR_PWM_BITS 16

#define OPTICAR_K_P 0.6
#define OPTICAR_K_I 0.3
#define OPTICAR_K_D 0.5

#define OPTICAR_MAX_RPM 394
#define OPTICAR_IMPULSES_PER_REVOLUTION 87.3
#define OPTICAR_WHEEL_DIAMETER 0.203 // [m]
#define OPTICAR_BASE_WIDTH 0.62       // [m]
#define OPTICAR_BASE_LENGTH 0.84      // [m]

#define OPTICAR_IMU_RATE 10 // [hz]
#define OPTICAR_ODO_RATE 10 // [hz]
#define OPTICAR_CMD_RATE 15 // [hz]
#define OPTICAR_DBG_RATE  5 // [hz]

#define OPTICAR_CMD_TIMEOUT 2.5 // [s]


#endif /* CONSTANTS_H_ */
